apiVersion: v1
kind: ServiceAccount
metadata:
  name: firewall-exporter
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: firewall-exporter
rules:
- apiGroups:
  - "firewall.metal-stack.io"
  resources:
  - firewallmonitors
  - firewallmonitors/status
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: firewall-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: firewall-exporter
subjects:
- kind: ServiceAccount
  name: firewall-exporter
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firewall-exporter
  labels:
    app: firewall-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firewall-exporter
  template:
    metadata:
      labels:
        app: firewall-exporter
    spec:
      containers:
        - name: firewall-exporter
          command:
            - /firewall-exporter
          args:
            - start
          image: ghcr.io/mwennrich/firewall-exporter:latest
          ports:
            - containerPort: 9080
              name: metrics
          securityContext:
            runAsUser: 999
            allowPrivilegeEscalation: false
            runAsNonRoot: true
      serviceAccount: firewall-exporter
      serviceAccountName: firewall-exporter
